name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/my-app/
          remote_host: ec2-54-218-8-12.us-west-2.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: SSH into remote server and start server
        run: |
          ssh ubuntu@ec2-54-218-8-12.us-west-2.compute.amazonaws.com -i ${{ secrets.SSH_PRIVATE_KEY }} 'cd /var/www/my-app && pm2 start /var/www/my-app/dist/index.js --name "my-app" --watch'
